# Generated by Django 5.2.3 on 2025-10-07 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rut_comercial', models.CharField(max_length=20)),
                ('nombre_marca', models.CharField(max_length=100)),
                ('rubro', models.CharField(choices=[('ROP', 'Ropa'), ('CAL', 'Calzado'), ('ACC', 'Accesorios'), ('DEP', 'Deportes'), ('OTR', 'Otros')], max_length=3)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajaConNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('puesto', models.CharField(choices=[('VEN', 'Vendedor'), ('LID', 'Líder de Equipo')], max_length=3)),
                ('mensaje', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('CHILEXPRESS', 'Chilexpress'), ('STARKEN', 'Starken'), ('CORREOS_CHILE', 'Correos de Chile'), ('BLUE_EXPRESS', 'Blue Express')], default='CHILEXPRESS', max_length=20)),
                ('marcas_compradas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marcas compradas')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('RM', 'Región Metropolitana de Santiago'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('VI', 'Región de O’Higgins'), ('VII', 'Región del Maule'), ('VIII', 'Región del Biobío'), ('IX', 'Región de La Araucanía'), ('XIV', 'Región de Los Ríos'), ('X', 'Región de Los Lagos'), ('XI', 'Región de Aysén'), ('XII', 'Región de Magallanes'), ('XV', 'Región de Arica y Parinacota'), ('XVI', 'Región de Ñuble')], max_length=4)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('monto_carrito', models.IntegerField()),
                ('costo_envio', models.IntegerField()),
                ('total_pagar', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('tipo', models.CharField(choices=[('REL', 'Reloj'), ('BUF', 'Bufanda'), ('CIN', 'Cinturón'), ('COL', 'Collar'), ('GOR', 'Gorra'), ('PUL', 'Pulseras')], default='REL', max_length=3)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3)),
                ('color', models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Piernas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3)),
                ('color', models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3)),
                ('subcategoria', models.CharField(choices=[('JEA', 'Jeans'), ('BUS', 'Buso'), ('SHT', 'Short'), ('FAL', 'Falda'), ('VES', 'Vestidos')], default='JEA', max_length=3)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Tronco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3)),
                ('color', models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3)),
                ('subcategoria', models.CharField(choices=[('POL', 'Poleras'), ('PLN', 'Poleron'), ('CAM', 'Camisas')], default='POL', max_length=3)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Zapatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3)),
                ('color', models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3)),
                ('subcategoria', models.CharField(choices=[('ZAP', 'Zapatillas'), ('BOT', 'Botos'), ('SAN', 'Sandalias'), ('MOC', 'Mocasines'), ('PAN', 'Pantuflas')], default='ZAP', max_length=3)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
    ]
