# Generated by Django 5.2.3 on 2026-01-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_preferenciasusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100, verbose_name='Nombre del Spot')),
                ('categorias', models.CharField(max_length=255, verbose_name='Categorías que vende')),
            ],
        ),
    ]
