# Generated by Django 5.2.3 on 2026-01-27 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_marca_tienda_marca_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='tienda_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='app.tienda', verbose_name='Tienda Asignada (Trabajador)'),
        ),
    ]
