# Generated by Django 5.2.3 on 2026-01-31 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_historialmodificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_modelo', models.CharField(max_length=100, verbose_name='Modelo del Producto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('tipo_producto', models.CharField(max_length=50, verbose_name='Categoría')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Baja')),
                ('motivo', models.CharField(default='Eliminación manual desde inventario', max_length=255, verbose_name='Motivo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Historial de Eliminación',
                'verbose_name_plural': 'Historial de Eliminaciones',
            },
        ),
    ]
