# ==========================================
# COMPILACION AUTOMATICA DE PROYECTO DJANGO
# ARCHIVO: Compilado_Settings.py
# FECHA: 2026-01-26 15:12:18
# ==========================================

--------------------------------------------------
# ARCHIVO: settings.py
# RUTA: C:\Users\juanl\Git\PROYECTOS\UrbanStore\UStore\UStore\settings.py
--------------------------------------------------

"""
Django settings for UStore project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q8=n480=z)46up8rb^gfwd6h9(k+4)o8v$(+gld9sh&f5q%o*('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # --- UNFOLD (Debe ir antes de django.contrib.admin) ---
    "unfold",
    "unfold.contrib.filters",  # Soporte para django-filter
    "unfold.contrib.forms",    # Soporte para formularios personalizados
    "unfold.contrib.import_export", # Soporte para import-export
    "unfold.contrib.guardian",      # Soporte para guardian
    "unfold.contrib.simple_history",# Soporte para simple-history
    
    # "admin_interface",  <-- COMENTADO: Unfold reemplaza esto
    # "colorfield",       <-- COMENTADO: Conflicto visual con Unfold
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- LIBRERIAS ADICIONALES INSTALADAS ---
    'import_export',
    'guardian',
    'simple_history',
    'django_filters',

    'app.apps.AppConfig',
    'django.contrib.humanize',
]

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware', # Middleware para historial
]

ROOT_URLCONF = 'UStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'urbanstore_db',
        'USER': 'urbanstore_user',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'app/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Configuración de sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CART_SESSION_ID = 'cart'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Transbank Config
TRANSBANK_API_KEY_ID = '597055555532'
TRANSBANK_API_KEY_SECRET = '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
TRANSBANK_RETURN_URL = 'http://localhost:8000/commit-pay/'

# =========================================================
# CONFIGURACION DE DJANGO-UNFOLD (ADMIN UI)
# Paleta: #0F0F0F (Bg), #202020 (Card), #5DD62C (Primary)
# =========================================================

UNFOLD = {
    "SITE_TITLE": "Administración UrbanStore",
    "SITE_HEADER": "UrbanStore",
    "SITE_URL": "/",
    # "SITE_ICON": lambda request: static("icon.svg"),  # Descomentar si tienes icono

    # Mapeo de colores personalizados (Tailwind RGB)
    # Primary 500 = #5DD62C (93 214 44)
    # Primary 600 = #337418 (51 116 24)
    "COLORS": {
        "primary": {
            "50": "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "74 222 128",
            "500": "93 214 44",   # Tu Verde Brillante
            "600": "51 116 24",   # Tu Verde Oscuro
            "700": "21 128 61",
            "800": "22 101 52",
            "900": "20 83 45",
            "950": "5 46 22",
        },
    },

    # Inyección de CSS para forzar el fondo negro profundo (#0F0F0F)
    # ya que Tailwind por defecto usa grises muy oscuros, pero no negro total.
    "STYLES": [
        lambda request: """
            <style>
                /* Fondo Principal */
                body, .bg-gray-50, .dark\:bg-gray-900 { 
                    background-color: #0F0F0F !important; 
                    color: #F8F8F8 !important;
                }
                
                /* Contenedores y Sidebar (Gris #202020) */
                .bg-white, .dark\:bg-gray-800, aside { 
                    background-color: #202020 !important; 
                    border-color: #333333 !important;
                }
                
                /* Ajuste de inputs para que se vean bien en fondo oscuro */
                input, select, textarea {
                    background-color: #1a1a1a !important;
                    border-color: #333333 !important;
                    color: #F8F8F8 !important;
                }
                
                /* Textos en hover */
                a:hover {
                    color: #5DD62C !important;
                }
            </style>
        """
    ],

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Catálogo de Productos"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Marcas"),
                        "icon": "label",
                        "link": reverse_lazy("admin:app_marca_changelist"),
                    },
                    {
                        "title": _("Tronco (Poleras/Camisas)"),
                        "icon": "checkroom",
                        "link": reverse_lazy("admin:app_tronco_changelist"),
                    },
                    {
                        "title": _("Piernas (Pantalones)"),
                        "icon": "accessibility_new",
                        "link": reverse_lazy("admin:app_piernas_changelist"),
                    },
                    {
                        "title": _("Zapatos"),
                        "icon": "hiking",
                        "link": reverse_lazy("admin:app_zapatos_changelist"),
                    },
                    {
                        "title": _("Accesorios"),
                        "icon": "watch",
                        "link": reverse_lazy("admin:app_complemento_changelist"),
                    },
                ],
            },
            {
                "title": _("Ventas & Logística"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Envíos"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:app_envio_changelist"),
                    },
                ],
            },
            {
                "title": _("Comunidad"),
                "separator": True,
                "items": [
                    {
                        "title": _("Mensajes de Contacto"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:app_contacto_changelist"),
                    },
                    {
                        "title": _("Solicitudes de Trabajo"),
                        "icon": "work",
                        "link": reverse_lazy("admin:app_trabajaconnosotros_changelist"),
                    },
                    {
                        "title": _("Solicitudes de Socios"),
                        "icon": "handshake",
                        "link": reverse_lazy("admin:app_sesocio_changelist"),
                    },
                ],
            },
            {
                "title": _("Accesos y Seguridad"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}

--------------------------------------------------
# ARCHIVO: urls.py
# RUTA: C:\Users\juanl\Git\PROYECTOS\UrbanStore\UStore\UStore\urls.py
--------------------------------------------------

"""
URL configuration for UStore project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views  # Importa views normalmente

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('Usuarios/IniciarSesion/', views.IniciarSesion, name="IniciarSesion"),
    path('Usuarios/cerrar_sesion/', views.cerrar_sesion, name="cerrar_sesion"),
    path('carrito/', views.carrito, name='carrito'),
    path('update_cart/', views.update_cart, name='update_cart'),
    
    # Rutas actualizadas (sin decoradores externos)
    path('producto/Administracion/', views.Administracion, name="Administracion"),
    path('producto/agregar_producto/', views.agregar_producto, name="agregar_producto"),
    path('producto/agrega_marca/', views.agrega_marca, name="agrega_marca"),
    path('producto/modificar/', views.modificar, name="modificar"),
    path('producto/eliminar/', views.eliminar, name="eliminar"),
    path('Usuarios/Admin_User/', views.Admin_User, name="Admin_User"),
    path('Ventas/Envio/', views.envio_view, name="Envio"),
    path('Ventas/Pago/', views.pago_view, name="Pago"),
    path('commit-pay/', views.commit_pay_view, name="commit_pay"),
    path('Usuarios/FormularioEnvio/', views.FormularioEnvio, name="FormularioEnvio"),
    path('marcar-procesado/<int:envio_id>/', views.marcar_procesado, name='marcar_procesado'),
    path('exportar-envios-no-procesados/', views.exportar_envios_no_procesados, name='exportar_envios_no_procesados'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

